### ISSUE TITLE
Wha are athe available stream names?

### ISSUE THREAD

**Issue by jrichardsz** [insight-platform/Fake-RTSP-Stream#4]
Excellent work!

The readme says

> To get the access to streams use: rtsp://machine-ip:8554/\<stream-name\> URL.

But I cannot find the exact stream name to build the url

I tried with VLC

![image](https://github.com/insight-platform/Fake-RTSP-Stream/assets/3322836/4131cace-83d2-48f2-af01-b04f4ddf108d)

All this urls 

```
rtsp://127.0.0.1:8554/stream
rtsp://127.0.0.1:8554/stream1
rtsp://127.0.0.1:8554/testsrc_01.mp4
rtsp://127.0.0.1:8554/local-loop
rtsp://127.0.0.1:8554/city-traffic
rtsp://127.0.0.1:8554/concatenated-sample
```

but in all the attempts, vlc showed an empty screen and the error in the server was:

```
fake-rtsp-stream-rtsp-server-1 | 2024/02/04 16:16:28 INF [RTSP] [conn 192.168.64.1:35388] opened
fake-rtsp-stream-rtsp-server-1 | 2024/02/04 16:16:28 INF [RTSP] [session 52c16edc] created by 192.168.64.1:35388
fake-rtsp-stream-rtsp-server-1 | 2024/02/04 16:16:28 INF [RTSP] [conn 192.168.64.1:35388] closed: invalid URL ((null))
fake-rtsp-stream-rtsp-server-1 | 2024/02/04 16:16:28 INF [RTSP] [session 52c16edc] destroyed: not in use
fake-rtsp-stream-rtsp-server-1 | 2024/02/04 16:16:28 INF [RTSP] [conn 192.168.64.1:35396] opened
fake-rtsp-stream-rtsp-server-1 | 2024/02/04 16:16:28 INF [RTSP] [conn 192.168.64.1:35396] closed: EOF
```

**Comment by bwsw** [comment]
Hello, the stream name corresponds to the one specified in the source.

**Comment by bwsw** [comment]
Hello, look at the compose:

```
  city-traffic:
    image: linuxserver/ffmpeg:version-4.4-cli
    links:
      - "rtsp-server:rtsp-server"
    depends_on:
      - rtsp-server
    command: -re -stream_loop -1 -i https://eu-central-1.linodeobjects.com/savant-data/demo/Free_City_Street_Footage.mp4 -c copy -bsf:v h264_mp4toannexb -f rtsp rtsp://rtsp-server:8554/city-traffic
```

If ffmpeg casts to `rtsp://rtsp-server:8554/city-traffic`, the name is `city-traffic`.
